### ISSUE TITLE
Add action to prevent changes to release files

### ISSUE THREAD

**Issue by juliapampus** [International-Data-Spaces-Association/ids-specification#210]
We tend to accidentally change the files in the `release` folder. A GitHub action could prevent this: https://github.com/xalvarez/prevent-file-change-action.

```yaml
- name: Prevent file change
  uses: xalvarez/prevent-file-change-action@v1
  with:
    githubToken: ${{ secrets.GITHUB_TOKEN }}
    pattern: releases/.*
    allowNewFiles: true
```
`allowNewFiles: true` to avoid that the action fails when we add a new release.
